'use client';
import {useState,useEffect,type ReactNode} from 'react';
import {Orbit,ShieldCheck} from 'lucide-react';
import {api,type Account} from './client';
export function AuthShell({children}:{children:(account:Account)=>ReactNode}){
 const [account,setAccount]=useState<Account|null>(null),[ready,setReady]=useState(false),[setup,setSetup]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState('');
 useEffect(()=>{async function load(){try{const s=await api<{setup:boolean}>('/auth/status');setSetup(s.setup);if(!s.setup)try{setAccount(await api<Account>('/auth/me'))}catch{setAccount(null)}}catch(e){setError((e as Error).message)}finally{setReady(true)}}void load();const expired=()=>{setAccount(null);setPassword('')};window.addEventListener('orbit-session-expired',expired);return()=>window.removeEventListener('orbit-session-expired',expired)},[]);
 if(!ready)return <div className="auth-screen">Abrindo seu workspace...</div>;
 if(account)return children(account);
 return <div className="auth-screen"><form className="auth-card" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api(setup?'/auth/setup':'/auth/login','POST',{name,email,password});setAccount(await api<Account>('/auth/me'));setSetup(false);setPassword('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><div className="brand"><Orbit/>orbit.</div><span className="eyebrow">PROJETOS, PESSOAS E ENTREGAS</span><h1>{setup?'Seu workspace começa aqui.':'Bom ter você de volta.'}</h1><p>{setup?'Crie sua conta administradora para configurar a equipe e organizar as próximas sprints.':'Entre para acompanhar o trabalho do seu time.'}</p>{setup&&<label className="field"><span>Seu nome</span><input required maxLength={80} autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label>}<label className="field"><span>E-mail</span><input type="email" required maxLength={160} autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field"><span>Senha</span><input aria-label="Senha" type="password" required minLength={setup?12:1} maxLength={128} autoComplete={setup?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)}/>{setup&&<small>Use pelo menos 12 caracteres.</small>}</label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="button primary full" disabled={busy}>{busy?'Aguarde...':setup?'Criar workspace':'Entrar'}</button><div className="auth-foot"><ShieldCheck size={16}/>Dados neste computador · Sessão de 8 horas</div></form></div>
}
