"use strict";
const $=id=>document.getElementById(id);
const state={token:"",task:null,hash:null,files:{},health:null};
let toastTimer;
function toast(text,error=false){const box=$("message");box.textContent=text;box.className=error?"error":"";box.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>box.hidden=true,9000);}
async function api(path,body){const headers={Authorization:"Bearer "+state.token};const opts={headers,cache:"no-store"};if(body!==undefined){opts.method="POST";headers["Content-Type"]="application/json";opts.body=JSON.stringify(body);}const response=await fetch(path,opts);let data;try{data=await response.json();}catch{throw Error("Resposta inválida do servidor local.");}if(!response.ok)throw Error(data.error||"Erro HTTP "+response.status);return data;}
function bind(id,action,event="submit"){const element=$(id);element.addEventListener(event,async e=>{e.preventDefault();const button=element.tagName==="BUTTON"?element:element.querySelector('button[type=submit],button');if(button)button.disabled=true;try{await action(e);}catch(err){toast(err.message,true);}finally{if(button)button.disabled=false;}});}
function text(tag,value,cls){const el=document.createElement(tag);el.textContent=value;if(cls)el.className=cls;return el;}
function item(parent,title,meta){const box=document.createElement("div");box.className="item";box.append(text("h3",title),text("div",meta,"meta"));parent.append(box);return box;}
function button(parent,label,action,cls="secondary"){const b=text("button",label,cls);b.type="button";b.addEventListener("click",async()=>{b.disabled=true;try{await action();}catch(err){toast(err.message,true);}finally{b.disabled=false;}});parent.append(b);return b;}
const scope=()=>$("scope").value;
function needProject(){if(scope()==="global")throw Error("Selecione um projeto no campo Escopo autorizado.");return scope();}
async function refreshHealth(){state.health=await api("/api/health");$("connection").textContent=state.health.offline?"Local · rede desligada":"Local · pesquisa autorizada";const s=state.health.stats;$("stats").textContent=`${s.projects} projetos · ${s.sources} fontes · ${s.chunks} trechos`;
$("research-status").textContent=(state.health.offline?"Rede desativada. Cópias já salvas ainda podem ser consultadas.":"Pesquisa habilitada somente nos domínios: "+state.health.allowed_domains.join(", "));}
async function refreshProjects(){const projects=await api("/api/projects");const current=scope();$("scope").replaceChildren(new Option("Biblioteca global","global"));$("projects").replaceChildren();for(const p of projects){$("scope").append(new Option(p.name,p.id));const box=item($("projects"),p.name,p.root);button(box,"Indexar",async()=>{const job=await api("/api/jobs/index",{project_id:p.id});toast("Indexação enfileirada: "+job.id);await refreshJobs();});}if([...$("scope").options].some(o=>o.value===current))$("scope").value=current;}
async function refreshSources(){const sources=await api("/api/sources?scope="+encodeURIComponent(scope()));$("sources").replaceChildren();for(const s of sources){const box=item($("sources"),s.title,s.kind+" · "+s.checked_at);button(box,"Remover fonte",async()=>{if(!confirm("Remover essa fonte e seus derivados da memória? Isso não apaga pesos já treinados."))return;await api("/api/sources/delete",{source_id:s.id,scope:scope()});await refreshSources();await refreshHealth();},"danger");}if(!sources.length)$("sources").append(text("p","Ainda não há fontes nesse escopo.","muted"));}
async function refreshTasks(){const tasks=await api("/api/tasks");$("tasks").replaceChildren();for(const t of tasks){const box=item($("tasks"),t.instruction,t.state+" · "+t.created_at);button(box,"Revisar",()=>selectTask(t.id));}}
async function selectTask(id){state.task=id;const data=await api("/api/tasks/"+id);state.hash=data.task.proposal_hash;$("task-state").textContent=data.task.state+" · "+id;$("diff").textContent=data.diff||"";const snapshot=await api("/api/tasks/"+id+"/files");state.files=snapshot.files;$("task-file").replaceChildren(new Option("Selecione um arquivo",""));for(const p of Object.keys(state.files))$("task-file").append(new Option(p,p));if(data.proposal)$("proposal").value=JSON.stringify(data.proposal.changes.map(c=>({path:c.path,before_sha256:c.before_sha256,content:c.content})),null,2);else $("proposal").value="";}
async function refreshJobs(){const jobs=await api("/api/jobs");$("jobs").replaceChildren();for(const job of jobs){const box=item($("jobs"),job.kind+" · "+job.state,job.id+" · "+job.created_at);if(job.error)box.append(text("p",job.error));if(job.result){const details=document.createElement("details");details.append(text("summary","Resultado"),text("pre",JSON.stringify(job.result,null,2)));box.append(details);}if(["queued","running"].includes(job.state))button(box,"Cancelar",async()=>{await api("/api/jobs/"+job.id+"/cancel",{});await refreshJobs();},"danger");}}
async function refreshModels(){const models=await api("/api/models");$("models").replaceChildren();for(const m of models){const box=item($("models"),m.directory,"Experimento CPU · não qualificado para programar");box.append(text("p",`${m.parameter_count} parâmetros · ${m.total_steps} passos · perda de validação ${m.final_validation_loss.toFixed(4)}`));}if(!models.length)$("models").append(text("p","Nenhum experimento registrado. Não há modelo pré-treinado escondido.","muted"));}
bind("login-form",async()=>{state.token=$("token").value.trim();await refreshHealth();$("token").value="";$("login").hidden=true;$("workspace").hidden=false;await refreshProjects();await refreshSources();await refreshTasks();await refreshModels();await refreshJobs();});
bind("project-form",async()=>{await api("/api/projects",{name:$("project-name").value,root:$("project-root").value});await refreshProjects();await refreshHealth();toast("Pasta cadastrada. Selecione-a no escopo e indexe os arquivos.");});
bind("note-form",async()=>{await api("/api/import",{scope:scope(),title:$("note-title").value,content:$("note-content").value});await refreshSources();await refreshHealth();toast("Nota guardada para consulta, sem treinamento automático.");});
bind("consult-form",async()=>{const data=await api("/api/consult",{query:$("query").value,scope:scope(),include_global:$("include-global").checked});$("consult-reason").textContent=data.reason+" · "+data.notice;$("evidence").replaceChildren();for(const e of data.evidence){const box=item($("evidence"),e.title,`Fonte ${e.source_id} · trecho ${e.chunk_id} · linhas ${e.start_line}–${e.end_line}`);box.append(text("pre",e.text));if(e.locator.startsWith("https://")){const a=text("a","Abrir fonte original");a.href=e.locator;a.target="_blank";a.rel="noopener noreferrer";box.append(a);}}if(!data.evidence.length)$("evidence").append(text("p","Nenhuma evidência local encontrada. Importe uma fonte ou faça uma pesquisa autorizada."));});
bind("task-form",async()=>{const task=await api("/api/tasks",{project_id:needProject(),instruction:$("instruction").value});await refreshTasks();await selectTask(task.id);toast("Cópia criada. Prepare a proposta; o original continua intacto.");});
bind("load-file",async()=>{if(!state.task||!$("task-file").value)throw Error("Selecione tarefa e arquivo.");const path=$("task-file").value;const data=await api("/api/tasks/"+state.task+"/file?path="+encodeURIComponent(path));$("proposal").value=JSON.stringify([{path,before_sha256:state.files[path],content:data.content}],null,2);},"click");
bind("proposal-form",async()=>{if(!state.task)throw Error("Selecione uma tarefa.");const data=await api("/api/tasks/"+state.task+"/proposal",{changes:JSON.parse($("proposal").value),allow_test_changes:$("allow-tests").checked});state.hash=data.proposal_hash;$("diff").textContent=data.diff;await refreshTasks();toast("Alteração preparada somente na cópia. Revise o diff antes de aplicar.");});
bind("apply-task",async()=>{if(!state.task||!state.hash)throw Error("Prepare uma proposta primeiro.");if(!confirm("Aplicar a proposta revisada no projeto original? Os hashes serão conferidos antes da escrita."))return;await api("/api/tasks/"+state.task+"/apply",{proposal_hash:state.hash,accept_without_tests:$("without-tests").checked});await selectTask(state.task);await refreshTasks();toast("Proposta aplicada; o diário de recuperação foi preservado.");},"click");
bind("reject-task",async()=>{if(!state.task)throw Error("Selecione uma tarefa.");await api("/api/tasks/"+state.task+"/reject",{});await selectTask(state.task);await refreshTasks();},"click");
bind("recover-task",async()=>{if(!state.task)throw Error("Selecione uma tarefa.");await api("/api/tasks/"+state.task+"/recover",{});await selectTask(state.task);},"click");
bind("verify-task",async()=>{if(!state.task)throw Error("Selecione uma tarefa.");await api("/api/tasks/"+state.task+"/verify",{kind:$("verify-kind").value,project_file:$("verify-project").value});toast("Verificação enfileirada. Falta de sandbox nunca executa código diretamente no notebook.");await refreshJobs();},"click");
bind("research-form",async()=>{await api("/api/jobs/research",{scope:scope(),urls:$("research-urls").value.split("\n").map(s=>s.trim()).filter(Boolean)});toast("Coleta/cache enfileirado; acompanhe Atividade.");await refreshJobs();});
bind("train-form",async()=>{await api("/api/jobs/train",{manifest:$("train-manifest").value,steps:Number($("train-steps").value),batch_size:Number($("train-batch").value),approved_dataset:$("approve-dataset").checked});toast("Experimento CPU enfileirado. Acompanhe Atividade; cancelar salva o checkpoint na próxima etapa segura.");await refreshJobs();});
bind("diagnose",async()=>{$("diagnostics").textContent=JSON.stringify(await api("/api/diagnostics"),null,2);},"click");
bind("refresh-jobs",refreshJobs,"click");
$("scope").addEventListener("change",()=>refreshSources().catch(e=>toast(e.message,true)));
for(const tab of document.querySelectorAll("[data-tab]"))tab.addEventListener("click",async()=>{for(const t of document.querySelectorAll("[data-tab]"))t.classList.toggle("active",t===tab);for(const panel of document.querySelectorAll("[data-panel]"))panel.hidden=panel.dataset.panel!==tab.dataset.tab;try{if(tab.dataset.tab==="activity")await refreshJobs();if(tab.dataset.tab==="training")await refreshModels();await refreshHealth();}catch(e){toast(e.message,true);}});
